name: swinvit_env
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - timm
  - webdataset
  - wget
  - pathlib
  - pip
  - pytorch
  - tqdm
  - pytorch-cuda=11.7  
  - pip:
      - neptune-client